# Functional programming divides a problem into set of functions 
# The map(), reduce(), filter() are used to modift the values in an data structure
# The filter function () function is used to create a new list from an older one and returns it 
# The map() function applies a particular function to every element of a list 
# The reduce() function returns a single value generated by calling the function on the first two iterms of the sequence, then on the result and the next items, and so on 
